var markers = [
 {
   "no": 1,
   "bencana": "Kebakaran Hutan dan Lahan",
   "tanggal": "2/18/2014",
   "jam": "",
   "bujur": 101.798,
   "lintang": 0.811881,
   "lokasi": "Kab. Bengkalis Kab. Indragiri Hulu Keb. Kampar Kab. Kuansing Kab. Pelalawan Kab. Siak Prov. Riau",
   "korban": "- Penderita ISPA sebanyak 30.249 jiwa, Pneumonia 562 jiwa, Asma 1.109 jiwa dan Iritasi Kulit 1.490 jiwa",
   "kerugian": "",
   "keterangan": "*Kronologis : - Kebakaran disebabkan oleh musim kemarau dan pembakaran lahan oleh warga sekitar *Upaya : - Satgas Udara : Telah melakukan water bombing dengan pesawat tempur Hawk 200, Heli Sikorsky, Pesawat SAR dan Pesawat dari Sinar Mas - Satgas Darat : Satuan Teritorial sudah memadamkan 27 titik api, Manggala Agni berhasil memadamkan 22 titik api *Kondisi Mutakhir : - BMKG : Visibilitas di Bandara SSK jam 18: 15 WIB adalah 200m dan diselimuti asap tebal"
 },
 {
   "no": 2,
   "bencana": "Kebakaran Hutan dan Lahan",
   "tanggal": "10/23/2013",
   "jam": "14:00 WITA",
   "bujur": 119.931,
   "lintang": -3.68783,
   "lokasi": "Gunung Sawah Ds. Puncak Indah Kec. Malili Kab. Luwu Timur Prov. Sulawesi Selatan",
   "korban": "Nihil",
   "kerugian": "area perkebunan terbakar (luas lahan masih dalam pendataan)",
   "keterangan": "*Kronologis: -Sumber api berasal dari lahan kebun sawit milik Sdr. Ayub warga transmigrasi desa puncak indah kec. Malili *Upaya: -BPBD Kab. Luwu Timur bersama unsur Muspika setempat melakukan pemadaman api"
 },
 {
   "no": 3,
   "bencana": "Kebakaran Hutan dan Lahan",
   "tanggal": "10/3/2013",
   "jam": "15:30 WIB",
   "bujur": 110.438,
   "lintang": -7.45401,
   "lokasi": "Daerah Taman Nasional Gunung Merbabu Dukuh Kajor Ds. Jrakah Kec. Selo Kab. Boyolali Prov. Jawa Tengah",
   "korban": "Nihil",
   "kerugian": "� 150 hektar lahan hutan terbakar",
   "keterangan": "Kronologis: -Faktor Alam dan kemungkinan ulah manusia Upaya: -BPBD Kab. Boyolali sudah mengirimkan logistik dan terus memantau titik api -MPA (masyarakat peduli api) memadamkan api secara manual dengan alat seadanya Kendala: -BPBD Kab. Boyolali tidak bisa mencapai lokasi dengan mobil pemadam atau mobil ranger karena kondisi medan sangat curam dan angin diatas ketinggian 2000 meter sangat besar"
 },
 {
   "no": 4,
   "bencana": "Kebakaran Lahan Gambut",
   "tanggal": "9/25/2013",
   "jam": "16.00:00 WITA",
   "bujur": 113.921,
   "lintang": -2.20994,
   "lokasi": "Jl. Trans Kalimantan Poros Selatan Ds. Klampangan Kec. Jekan raya Kota Palangkaraya Prov. Kalteng",
   "korban": "Korban Jiwa : Nihil",
   "kerugian": "Kerugian materil : � 2 Ha lahan gambut terbakar",
   "keterangan": "Kronologis : Asal api tidak diketahui siapa yg membakar Upaya : Tim gabungan posko dari manggala agni sudah memadamkan api dgn menggunakan 1 unit mobil pemadam"
 },
 {
   "no": 5,
   "bencana": "Kebakaran Hutan dan Lahan",
   "tanggal": "9/24/2013",
   "jam": "",
   "bujur": 114.722,
   "lintang": -3.49149,
   "lokasi": "Kota Banjar Baru Kab. Banjar Provinsi Kalimantan Selatan",
   "korban": "Nihil",
   "kerugian": "� 100 ha lahan gambut dan lahan pertanian terbakar",
   "keterangan": "*Kronologis : Kebakaran disebabkan karna musim panas yang masih berlangsung di daerah tersebut. *Upaya : -Pada tanggal 26 September 2013, BPBD mendirikan 2 unit posko di daerah bandara Samsudin Noor Banjarmasin dengan masing-masing anggota 15 orang. - Relawan dari Manggala Agni BPBD Kab. Banjar, Damkar dan BPBD Kota Banjar bersama-sama melakukan pemadaman api. - Damkar bersama BPBD mengerahkan 3 unit mobil pemadam kebakaran untuk memadamkan api"
 },
 {
   "no": 6,
   "bencana": "Kebakaran Hutan dan Lahan",
   "tanggal": "9/23/2013",
   "jam": "",
   "bujur": 96.1196,
   "lintang": 4.20613,
   "lokasi": "Prov. Aceh Kab. Aceh Barat Kec. Johan Pahlawan Ds. Kp. Juani Ds. Swaraya Ds. Ujung Blang Ds. Ujung Braso",
   "korban": "Nihil",
   "kerugian": "� 4 Ha lahan gambut terbakar",
   "keterangan": "Kronologis : - Diakibatkan pembukaan lahan baru oleh warga Desa tersebut dengan membakar lahan. Upaya : - BPBD telah membagikan 700 masker ke masyarakat Kec. Johan Pahlawan dan sekitarnya yang dilaksanakan pada hari Rabu - BPBD menghimbau agar warga tidak membuka lahan secara illegal - Lahan terbakar merupakan lahan gambut - Lokasi kebakaran dekat dengan gudang elpiji lalu BPBD melaukan penyiraman di lokasi GD. Elpiji Kendala : - BPBD kekurangan peralatan seperti selang - Lokasi sulit dijangkau"
 },
 {
   "no": 7,
   "bencana": "Kebakaran Hutan dan Lahan",
   "tanggal": "8/27/2013",
   "jam": "11.55 WIB",
   "bujur": 101.707,
   "lintang": 0.29335,
   "lokasi": "Prov. Riau",
   "korban": "Penderita ISPA: 15.346 Jiwa. Pneumonia: 943 Jiwa. Asma: 974 Jiwa. Iritasi Mata: 888 Jiwa. Iritasi Kulit: 998 Jiwa.",
   "kerugian": "Masih Pendataan",
   "keterangan": "Kondisi Mutakhir: - Jumlah titik api di Riau sebanyak 264 titik - Jarak Pandang mencapai 1 s/d 1,5 M. Kronologis: - kebakaran hutan belum dapat dipastikan penyebabnya. Upaya: - Pemantauan terus dilakukan. - Water bombing 84 kali oleh Helikopter Bolco dan 26 kali oleh Helikopter Sikorsky, 2.407 sorti, 91 liter, total 8.424,50 liter. - Hujan buatan dari TMC BPPT. - Pihak BKSDA Manggala Agni melakukan pemadaman titik api. - Dilakukan Sorti penerbangan dengan pesawat Casa A-9031 pada jam 14.51 - 16.34 WIB. Penyemaian awan dilakukan didaerah Meranti dan Siak pada ketinggian 6.200 - 7.600 feet dengan bahan semai yang terpakai sebanyak 1.000 kg. Puncak awan berkisar antara 7.000 feet. - Pengoperasian Ground Particulate Generator (GPG) : Pengoperasian GPG mulai jam 10.00 WIB sampai saat ini masih berlangsung, total larutan yang terpakai 120 liter. Operasi Satgas Darat : - Data Patroli Satgas Darat Penanggulangan asap dan Pemadaman Titik Api : 136 titik oleh TNI-AD, 5 titik oleh Pemda dan 64 titik oleh Masyarakat. Bantuan Logistik : - Selimut : 25 lembar. - Masker : 25.500 pcs - Tenda : 25 buah - Perlengkapan Dapur ; 300 set - Matras : 25 lembar - Kantong mayat : 100 buah - Family Kit : 150 set - Paket Tambahan : 100 paket - Paket Kesehatan : 100 paket - Kidsware : 50 set - Paket Sandang : 50 paket."
 },
 {
   "no": 8,
   "bencana": "Kebakaran",
   "tanggal": "7/31/2013",
   "jam": "16.30-18.00 WIB",
   "bujur": 117.091,
   "lintang": -0.52705,
   "lokasi": "RT 28,30,dan 37 Kel. Loa Bakung Kec. Sungai Kunjang Kota Samarinda Prov. Kalimantan Timur",
   "korban": "Nihil",
   "kerugian": "31 unit rumah tunggal, 10 unit rumah bangsal yang terdiri dari 49 KK 170 jiwa",
   "keterangan": "Kronologis : Kebakaran disebabkan oleh hubungan arus pendek listrik Upaya : BPBD Kota Samarinda beserta pihak kelurahan dan kecamatan sudah mendirikan posko pengungsian."
 },
 {
   "no": 9,
   "bencana": "Kebakaran Hutan dan Lahan",
   "tanggal": "7/9/2013",
   "jam": "19.00 WIB",
   "bujur": 101.47,
   "lintang": 0.5463,
   "lokasi": "Kota Pekan Baru, Prov. Riau",
   "korban": "Korban Dampak Kabut Asap : - Laporan penyakit dampak asap adalah 15.346 orang terkena ISPA, - 984 orang terkena Pnemonia. - 845 orang terkena Asma. - 923 orang terkena infeksi mata. - 1.094 orang mengalami iritasi kulit.",
   "kerugian": "",
   "keterangan": "Kegiatan : - TMC total 71 ton. - Water Bombing : 1.232 (742.000 liter) - Operasi Pemadaman Darat, jumlah personil 1.524 TNI/Polri dari Pusat dan 2.142 TNI/Polri dan BNPB. - 3.076 titik api berhasil dipadamkan. - Penegakan Hukum, 17 Kasus dengan 25 tersangka(1 koorporasi). Hasil Operasi : - Indeks kualitas udara menunjukan peningkatan. - Jarak pandang dalam meter menunjukan tipisnya kabut asap di udara, semakin jauh berarti semakin tipi pula kabut asapnya. Bantuan Logistik : - Selimut 25 lembar. - Masker 25.500 lembar. - Tenda gulung 25 lembar. - Perlengkapan dapur 300 paket. - Matras 25 lembar. - Kantong mayat 100 lembar. - Familiy kits 150 paket. - Paket tambahan perlengkapan makan 100 paket. - Paket kesehatan keluarga 100 paket. - Kidware 50 paket. - Paket sandang 50 paket."
 },
 {
   "no": 10,
   "bencana": "Kebakaran Hutan dan Lahan",
   "tanggal": "6/28/2013",
   "jam": "19.30 WIB",
   "bujur": 101.448,
   "lintang": 1.66698,
   "lokasi": "Kec. Mandau, Kab. Siak. Kec. Bukit Kapur, Kota Dumai, Prov. Riau",
   "korban": "Nihil",
   "kerugian": "2.500 s/d 3.000 ha area hutan terbakar. Kondisi Muktahir : - Info dari BMKG : - Titik api sudah menurun dari 265 menjadi 6. - 6 titik api yang terdata di 2 kabupaten (Kab. Dumai 5 titik dan kab. Siak 1 titik) - Pemadaman melalui water bombing dilakukan dengan 3 helikopter yang bergerak dari pukul 13.40-15.45 WIB sebanyak 47 kali. - Hujan lebat terjadi pada pukul 16.00-17.00 WIB.",
   "keterangan": "Upaya : - Pemadaman melalui waterbombing dilakukan dengan 3 helikopter dikonsentrasikan diatas wilayah Pelalawan dan Langgam. - Pemadaman darat dikonsentrasikan dititik api wilayah Siak, Bengkalis, Dumai, Rokan Hilir dan Rokan Hulu."
 },
 {
   "no": 11,
   "bencana": "Kebakaran Hutan dan Lahan",
   "tanggal": "6/20/2013",
   "jam": "",
   "bujur": 102.08,
   "lintang": 1.48972,
   "lokasi": "Desa Rimba Panjang dan Desa Siabu, Kec. Kuwok, kec. Tapung Hulu, Kec. Tiga Belas, Kec. Tambang, Kota kampar, Kab Pekan Raya, Prov. Riau",
   "korban": "Nihil",
   "kerugian": "- 800 ha lahan gambut terbakar sejak tanggal 18 Juni 2013, titik api berjumlah 148 titik. -Volume asap meningkat dan pengurangan jarak pandang. - Kabut asap di tanjung pinang dan Batam jarak pandang 300 m. - Di Kec. Tambang lahan seluas 30 ha terbakar. - Di Kec. Tiga Belas, Kota Kampar terdapat lahan yang terbakar, namun luasannya belum terdata. - Lokasi kejadian merupakan hutan gambut sehingga sulit untuk dipadamkan. Kondisi Muktahir : - Pemadaman kebakaran tetap dilanjutkan dan dilakukan penambahan personil dari berbagai unsur. - Di Desa Rimba Panjang, Kec. Tambang, Kab. Kampar masih terdapat asap namun tidak ditemukan adanya titik api. - Informasi dari warga dikatakan bahwa dalam kejadian ini terdapat unsur kesenggajaan dari ulah manusia, namun pelaku tidak dijumpai oleh petugas yang ada dilapangan.",
   "keterangan": "Upaya : - Hujan buatan difasilitasi oleh BNPB. - BPBD Riau telah membagikan 300 lembar masker. - BNPB, BPBD, TNI, POLRI, Manggala Agni, dan unsur masyarakat lainnya terus melakukan upaya pemadaman dilokasi kejadian. Kebutuhan Mendesak : - Dibutuhkan masker kurang lebih 8.000 lembar. - Penambahan alat pemadam kebakaran."
 },
 {
   "no": 12,
   "bencana": "Kebakaran Hutan",
   "tanggal": "9/25/2012",
   "jam": "15:00:00 WITA",
   "bujur": 115.356,
   "lintang": -8.22202,
   "lokasi": "Kawasan Gunung Batur, Kec. Kintamani, Kab. Bangli, Prov. Bali",
   "korban": "Nihil",
   "kerugian": "52 Ha hutan terbakar",
   "keterangan": "Kronologis: Kebakaran terjadi diperkirakan jumlah titik api sebanyak 10 titik yang terdapat disebelah barat dan utara lereng gunung batur. Upaya: - Pemadaman dilakukan secara manual oleh personil polisi hutan wilayah Bali Timur beserta warga sekitar dibantu Tagana, Kodim. - BPBD Kab. Badung menurunkan TRC dan 3 mobil Rescue, 1 mobil komando pemadam kebakaran."
 },
 {
   "no": 13,
   "bencana": "Kebakaran Hutan dan Lahan",
   "tanggal": "9/20/2012",
   "jam": "",
   "bujur": 112.643,
   "lintang": -7.71763,
   "lokasi": "Kawasan hutan lindung Konservasi Tahura R. Soerjo & Perhutani, Kab. Pasuruan, Prov. Jawa Timur",
   "korban": "Nihil",
   "kerugian": "300 Ha hutan lindung terbakar",
   "keterangan": "Upaya: - TRC BPBD Kab. Pasuruan sudah ke lokasi melakukan koordinasi dan identifikasi masalah akibat bencana kebakaran hutan. - Tim BPBD Kab. Pasuruan, tim Pengamanan Hutan Tahura, Kaliandra KTT , Tim SAR Pasuruan dan Tagana Menuju lokasi melakukan pemadaman sampai pkl. 05.00 Wib. Kebutuhan mendesak: - Perbaikan jaringan pipa air bersih - Peralatan personil pemadam kebakaran. - Dukungan logistik - Kendaraan Double gardan untuk mobilisasi warga dan logistik."
 },
 {
   "no": 14,
   "bencana": "Kebakaran Lahan dan Hutan",
   "tanggal": "9/19/2012",
   "jam": "10:00:00 WIB",
   "bujur": 110.46,
   "lintang": -1.21527,
   "lokasi": "Kec. Simpang Hilir, Kab. Kayong Utara, Prov. Kalimantan Barat",
   "korban": "Nihil",
   "kerugian": "50 Ha lahan terbakar, 1 rumah terbakar, 1 gereja, serta 1 sekolah",
   "keterangan": "- BPBD Prov. Kalbar, BPBD Kab. Kayong Utara tlh berkoordinasi dgn istansi terkait untuk penanganan Darurat. - Personel ada 28 org, yg terlibat Manggala Agni, Din. Perkebunan, Damkar, bpbd, Tagana. - Bupati meninjau langsung ke lokasi. - Api bru padam pkl. 20.00 wib. - Petugas mrlakukan blocking agar tdk meluas krn bsk akan ada Pilkada Gub. Kalbar."
 },
 {
   "no": 15,
   "bencana": "Kebakaran Hutan dan Lahan",
   "tanggal": "8/31/2012",
   "jam": "14:00:00 WITA",
   "bujur": 115.521,
   "lintang": -8.34659,
   "lokasi": "Hutan Gunung Agung Bagian Tenggara, Kec. Karangasem, Prov. Bali",
   "korban": "Nihil",
   "kerugian": "160 Ha Hutan terbakar",
   "keterangan": "- BPBD dan SKPD terkait sudah turun kelokasi untuk melakukan pemantauan - Sebanyak 80 personel turun kelokasi untuk membuat pembatas - Pukul 15.40 titik api mengarah ke timur memasuki Ds. Bebandum."
 },
 {
   "no": 16,
   "bencana": "Titik Hot Spot",
   "tanggal": "8/14/2012",
   "jam": "",
   "bujur": 102.438,
   "lintang": -1.48518,
   "lokasi": "Prov. Jambi",
   "korban": "Nihil",
   "kerugian": "Dalam Pendataan",
   "keterangan": "Kab. Batanghari: 9 titik hospot Kab. Bungo:5 titik hospot Kab. Merangin:8 titik hospot Kab. Sarolangun:8 titik hospot Kab. Tanjbtim:1 titik hospot Kab. Tebo:9 titik hospot Kab. Sei Penuh:1 titik hospot Kab. Tanjabarat:4 titik hospot Kab. THR:2 titik hospot"
 },
 {
   "no": 17,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 117.013,
   "lintang": 4.07734,
   "lokasi": "Provinsi Kalimatan Timur",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 18,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 117.464,
   "lintang": 2.77187,
   "lokasi": "Provinsi Kalimatan Timur",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 19,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 117.647,
   "lintang": 2.51269,
   "lokasi": "Provinsi Kalimatan Timur",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 20,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 116.082,
   "lintang": 0.525693,
   "lokasi": "Provinsi Kalimatan Timur",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 21,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 116.255,
   "lintang": 0.458499,
   "lokasi": "Provinsi Kalimatan Timur",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 22,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 117.282,
   "lintang": -0.117443,
   "lokasi": "Provinsi Kalimatan Timur",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 23,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 116.543,
   "lintang": -0.424613,
   "lokasi": "Provinsi Kalimatan Timur",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 24,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 115.525,
   "lintang": -0.5494,
   "lokasi": "Provinsi Kalimatan Timur",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 25,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 115.468,
   "lintang": -0.319023,
   "lokasi": "Provinsi Kalimatan Timur",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 26,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 116.024,
   "lintang": -1.81647,
   "lokasi": "Provinsi Kalimatan Timur",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 27,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 115.928,
   "lintang": -2.94916,
   "lokasi": "Provinsi Kalimatan Selatan",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 28,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 115.784,
   "lintang": -2.92036,
   "lokasi": "Provinsi Kalimatan Selatan",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 29,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 115.535,
   "lintang": -3.31392,
   "lokasi": "Provinsi Kalimatan Selatan",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 30,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 115.631,
   "lintang": -3.40992,
   "lokasi": "Provinsi Kalimatan Selatan",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 31,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 115.17,
   "lintang": -2.68999,
   "lokasi": "Provinsi Kalimatan Selatan",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 32,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 114.095,
   "lintang": -0.472608,
   "lokasi": "Provinsi Kalimatan Tengah",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 33,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 114.162,
   "lintang": -0.5494,
   "lokasi": "Provinsi Kalimatan Tengah",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 34,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 115.122,
   "lintang": -0.616594,
   "lokasi": "Provinsi Kalimatan Tengah",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 35,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 114.479,
   "lintang": -1.44211,
   "lokasi": "Provinsi Kalimatan Tengah",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 36,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 114.316,
   "lintang": -1.75888,
   "lokasi": "Provinsi Kalimatan Tengah",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 37,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 115.151,
   "lintang": -1.83567,
   "lokasi": "Provinsi Kalimatan Tengah",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 38,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 110.543,
   "lintang": 0.544891,
   "lokasi": "Provinsi Kalimatan Barat",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 39,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 112.674,
   "lintang": -0.242231,
   "lokasi": "Provinsi Kalimatan Barat",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 40,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 120.776,
   "lintang": -1.89327,
   "lokasi": "Provinsi Sulawesi Tengah",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 41,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 120.862,
   "lintang": -1.96046,
   "lokasi": "Provinsi Sulawesi Tengah",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 42,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 121.477,
   "lintang": -1.09655,
   "lokasi": "Provinsi Sulawesi Tengah",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 43,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 121.908,
   "lintang": -3.09315,
   "lokasi": "Provinsi Sulawesi Tenggara",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 44,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 122.12,
   "lintang": -3.45791,
   "lokasi": "Provinsi Sulawesi Tenggara",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 45,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 121.985,
   "lintang": -3.76508,
   "lokasi": "Provinsi Sulawesi Tenggara",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 46,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 122.273,
   "lintang": -3.98586,
   "lokasi": "Provinsi Sulawesi Tenggara",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 47,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 120.469,
   "lintang": -6.41442,
   "lokasi": "Provinsi Sulawesi Selatan",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 48,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 96.615,
   "lintang": 4.84526,
   "lokasi": "Provinsi Aceh",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 49,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 96.8742,
   "lintang": 4.81646,
   "lokasi": "Provinsi Aceh",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 50,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 96.8646,
   "lintang": 4.72047,
   "lokasi": "Provinsi Aceh",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 51,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 96.9798,
   "lintang": 4.76847,
   "lokasi": "Provinsi Aceh",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 52,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 96.9702,
   "lintang": 4.65328,
   "lokasi": "Provinsi Aceh",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 53,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 97.6229,
   "lintang": 4.56689,
   "lokasi": "Provinsi Aceh",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 54,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 97.4789,
   "lintang": 4.13493,
   "lokasi": "Provinsi Aceh",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 55,
   "bencana": "Titik Hot Spot",
   "tanggal": "10/31/2011",
   "jam": "13:26:00 WIB",
   "bujur": 97.1046,
   "lintang": 4.09654,
   "lokasi": "Provinsi Aceh",
   "korban": "",
   "kerugian": "",
   "keterangan": ""
 },
 {
   "no": 56,
   "bencana": "Kebakaran Lahan",
   "tanggal": "10/5/2011",
   "jam": "",
   "bujur": 113.796,
   "lintang": -1.8835,
   "lokasi": "Kota Palangkaraya",
   "korban": "",
   "kerugian": "3 lokasi kebakaran",
   "keterangan": ""
 },
 {
   "no": 57,
   "bencana": "kebakaran hutan",
   "tanggal": "10/4/2011",
   "jam": "",
   "bujur": 114.994,
   "lintang": -1.02511,
   "lokasi": "Kab. Barito Utara, Prov. Palangkaraya",
   "korban": "",
   "kerugian": "1 lokasi hotspot",
   "keterangan": ""
 },
 {
   "no": 58,
   "bencana": "kebakaran hutan",
   "tanggal": "10/4/2011",
   "jam": "",
   "bujur": 113.478,
   "lintang": -0.836057,
   "lokasi": "Kab. Gunung Mas, Prov. Kalimantan Tengah",
   "korban": "",
   "kerugian": "1 lokasi hotspot",
   "keterangan": ""
 },
 {
   "no": 59,
   "bencana": "kebakaran hutan",
   "tanggal": "10/4/2011",
   "jam": "",
   "bujur": 111.681,
   "lintang": -2.38318,
   "lokasi": "Kab. Kotawaringin Barat, Prov. Palangkaraya",
   "korban": "",
   "kerugian": "1 lokasi hotspot",
   "keterangan": ""
 },
 {
   "no": 60,
   "bencana": "kebakaran hutan",
   "tanggal": "10/4/2011",
   "jam": "",
   "bujur": 112.573,
   "lintang": -2.24243,
   "lokasi": "Kab. Kotawaringin Timur, Prov. Kalimantan Tengah",
   "korban": "",
   "kerugian": "1 lokasi hotspot",
   "keterangan": ""
 },
 {
   "no": 61,
   "bencana": "kebakaran hutan",
   "tanggal": "10/4/2011",
   "jam": "",
   "bujur": 113.837,
   "lintang": -2.73188,
   "lokasi": "Kab. Pulang Pisau, Prov. Kalimantan Tengah",
   "korban": "",
   "kerugian": "1 lokasi hotspot",
   "keterangan": ""
 },
 {
   "no": 62,
   "bencana": "kebakaran hutan",
   "tanggal": "10/4/2011",
   "jam": "",
   "bujur": 112.22,
   "lintang": -3.16708,
   "lokasi": "Kab. Seruyan, Prov. Kalimantan Tengah",
   "korban": "",
   "kerugian": "2 lokasi hotspot",
   "keterangan": ""
 },
 {
   "no": 63,
   "bencana": "Kebakaran Hutan",
   "tanggal": "9/27/2011",
   "jam": "10:00:00 WIB",
   "bujur": 110.425,
   "lintang": -7.48029,
   "lokasi": "Blok Tritis, Dk.Tumut, Ds.Jeragah, Prov.Jawa Tengah",
   "korban": "",
   "kerugian": "10 Ha hutan terbakar (data awal)",
   "keterangan": ""
 },
 {
   "no": 64,
   "bencana": "Kebakaran Hutan",
   "tanggal": "9/27/2011",
   "jam": "",
   "bujur": 109.664,
   "lintang": -7.31613,
   "lokasi": "G. Tangenan, Kab. Banjarnegara, Prov. Jawa Tengah",
   "korban": "Nihil",
   "kerugian": "36 ha Lahan terbakar",
   "keterangan": ""
 },
 {
   "no": 65,
   "bencana": "Kebakaran Hutan dan Lahan",
   "tanggal": "9/13/2011",
   "jam": "",
   "bujur": 103.933,
   "lintang": -3.3662,
   "lokasi": "Kab. Muara Enim, Sumsel",
   "korban": "",
   "kerugian": "terdapat 1 titik hotspot kebakaran hutan dan lahan",
   "keterangan": ""
 },
 {
   "no": 66,
   "bencana": "Kebakaran Hutan dan Lahan",
   "tanggal": "9/13/2011",
   "jam": "",
   "bujur": 103.422,
   "lintang": -3.84827,
   "lokasi": "Kab. Lahat, Prov. Sumsel",
   "korban": "",
   "kerugian": "Terdapat 4 hotspot kebakaran hutan dan lahan",
   "keterangan": ""
 },
 {
   "no": 67,
   "bencana": "Kebakaran Lahan Kelapa Sawit",
   "tanggal": "9/5/2011",
   "jam": "15:00:00 WIB",
   "bujur": 103.769,
   "lintang": -1.67826,
   "lokasi": "Ds.Muaro Gelam, Kab.Muaro Jambi, Prov.Jambi",
   "korban": "Nihil",
   "kerugian": "Kerugian mencapai 11.500 Ha lahan kelapa sawit. Lebih kurang 16 titik api di Kab. Muaro.",
   "keterangan": ""
 },
 {
   "no": 68,
   "bencana": "Kebakaran lahan",
   "tanggal": "9/1/2011",
   "jam": "15:00:00 WIB",
   "bujur": 103.72,
   "lintang": -1.4438,
   "lokasi": "Ds.Danau Lamo,Kec.Muaro Sebo,Prov.Jambi",
   "korban": "Nihil",
   "kerugian": "150 ha perkebunan kelapa sawit dan 15 ha persawahan",
   "keterangan": ""
 }
];